version: "3.8"

x-common: &common
  networks:
    - default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pancake}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pancake}
      POSTGRES_DB: ${POSTGRES_DB:-pancake}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pancake}"]
      interval: 10s
      timeout: 5s
      retries: 5
    <<: *common

  redis:
    image: bitnami/redis:7.2.5
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/bitnami/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-pancake}
    ports:
      - 6379:6379
    <<: *common

  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    <<: *common

  kibana:
    depends_on:
      - elasticsearch
    image: kibana:8.7.0
    container_name: kibana
    hostname: kibana
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    <<: *common

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local

networks:
  default:
    driver: bridge
