version: "3.8"

x-common: &common
  networks:
    - default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pancake}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pancake}
      POSTGRES_DB: ${POSTGRES_DB:-pancake}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pancake}"]
      interval: 10s
      timeout: 5s
      retries: 5
    <<: *common

  redis:
    image: bitnami/redis:7.2.5
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/bitnami/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-pancake}
    ports:
      - 6379:6379
    <<: *common

  pancake-dsc:
    build:
      context: .
    container_name: pancake-dsc
    hostname: pancake-dsc
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - postgres
      - redis
    networks:
      - default
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
